### ISSUE TITLE
往前的路都是坎

### ISSUE THREAD

**Issue by GoToBoy** [meijies/before-30-years-old#1]
相似的背景，尤其是好经典大部头书籍忽略基础的路线；
看完思考下这个阶段 往前哪里都是门槛...

**Comment by meijies** [comment]
没想到有人关注，看来我还得继续更新。
读书没必要逐字逐句地读，枯燥的内容索性跳过，否则太消磨热情了。

目标的话还是得分析核心竞争力，逐步积累深度。现实一点讲，出去面试，得要有亮点（某个知识点的有深度），否则会得再多，也让人觉得平庸，无法和其他竞争者区别开来

**Comment by tao1587** [comment]
你的动力从哪来 ，物质还是为了身边的人？

**Comment by meijies** [comment]
来自于多方面
第一：我有时间（ 我不玩游戏，不刷微博，偶尔刷知乎，不看小说，平常看看电影，电视剧等。）
第二：写很酷的，不重复的代码某种程度上成为我兴趣的一部分了
第三：物质，谁不想过更好的生活呢？
第四：成就感，价值感，想写很酷的应用
第五：缺乏勇气，对我来说写代码肯定不是最好的选择，但也算不错的选择。还没有勇气放弃现有的一切，重新出发。

**Comment by meijies** [comment]
@GoToBoy  希望这个能帮到你
https://github.com/codefollower/My-Blog/issues/1
